layout_spectrum: 0.255102
typography_spectrum: 0.4280344
color:
  saturation: 0.9527473
  lightness: 0.6102224
  brandStrength: 0.991732
  rhythmicContrast: 0.3495995
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Editions Violone
